POST http://localhost:8080/api/v1/accounts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImRlZmF1bHQiXSwib3JnYW5pemF0aW9uIjoidHJhaW5pbmciLCJleHAiOjE1NTk4MTg3MzIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiMGU1YzBkZjctYjY0Ny00NDIwLTk3MTEtZjY2NjNhOWRhMmViIiwiY2xpZW50X2lkIjoiYXM0MDAifQ.2GLHUze1pyb6pioOIomsz0bHrYeBQg6zOwLP1uOoJD4

###

GET http://localhost:8080/api/v1/accounts/10
Accept: application/json

###

GET http://localhost:8080/api/v1/accounts?pageNumber=0&pageSize=10
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImRlZmF1bHQiXSwib3JnYW5pemF0aW9uIjoidHJhaW5pbmciLCJleHAiOjE1NTk4MTg3MzIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiMGU1YzBkZjctYjY0Ny00NDIwLTk3MTEtZjY2NjNhOWRhMmViIiwiY2xpZW50X2lkIjoiYXM0MDAifQ.2GLHUze1pyb6pioOIomsz0bHrYeBQg6zOwLP1uOoJD4

###

DELETE http://localhost:8080/api/v1/accounts/10
Accept: application/json

###

POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin&grant_type=password&client_id=as400

###

POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImRlZmF1bHQiXSwib3JnYW5pemF0aW9uIjoidHJhaW5pbmciLCJleHAiOjE1NTk4MTI2NDIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNzE0NGI2MGQtNjNhNC00YjY3LTk3YzktMGM4ZWYyMzI0ZDdjIiwiY2xpZW50X2lkIjoiYXM0MDAifQ.ghWxbNFUVi7DYz8V5AFDkUvXQrsW6t3aHz1erTcfs_U&grant_type=refresh_token&client_id=as400

###

GET http://localhost:8081/api/v1/users/active
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImRlZmF1bHQiXSwib3JnYW5pemF0aW9uIjoidHJhaW5pbmciLCJleHAiOjE1NTk4MTI2NDIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNzE0NGI2MGQtNjNhNC00YjY3LTk3YzktMGM4ZWYyMzI0ZDdjIiwiY2xpZW50X2lkIjoiYXM0MDAifQ.ghWxbNFUVi7DYz8V5AFDkUvXQrsW6t3aHz1erTcfs_U

###

DELETE http://localhost:8081/api/v1/users/active
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImRlZmF1bHQiXSwib3JnYW5pemF0aW9uIjoidHJhaW5pbmciLCJleHAiOjE1NTk4MTA0NjYsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiZWE2NzFkMGMtNmFmOC00Yjk4LThlYzMtMzg4Y2RiNmYzY2Y3IiwiY2xpZW50X2lkIjoiYXM0MDAifQ._QaNhJJz6KKdAzH_ZjvyEtXxpdk8EknraL2-mrugXAI

###
